"""Gives the page's data files a version in their name, so nginx can cache them for a year (see nginx/default.conf).

publish('cities.json', text) writes site/cities.<hash>.json, where <hash> is the first 10 hex digits of the SHA-256 of
the content, deletes the older versions of that file, and records the new name in site/js/data-files.js:

    export const DATA={"cities.json":"cities.1a2b3c4d5e.json", ...};

The page imports DATA and fetches DATA['cities.json'].  Changed content gets a new name, so a browser can never keep
using an outdated copy, and unchanged content keeps its name (and stays in the browser cache).  Only the generated
data-files.js has to be revalidated on each visit, which nginx does for everything that is not a data file.
"""
import hashlib
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.join(HERE, '..', 'site')
MANIFEST = os.path.join(SITE, 'js', 'data-files.js')
HASH_LEN = 10          # keep in step with the location regex in nginx/default.conf
HEAD = '// Generated by tools/data_files.py: the current name of each data file.  Do not edit.\nexport const DATA='


def read_manifest():
    try:
        src = open(MANIFEST, encoding='utf-8').read()
    except FileNotFoundError:
        return {}
    return json.loads(src[len(HEAD):].rstrip().rstrip(';'))


def versioned_name(name, data):
    stem, ext = os.path.splitext(name)
    return f'{stem}.{hashlib.sha256(data).hexdigest()[:HASH_LEN]}{ext}'


def publish(name, text):
    """Write `text` as the new version of site/<name>; returns the file name the page should fetch."""
    data = text.encode('utf-8')
    new = versioned_name(name, data)
    stem, ext = os.path.splitext(name)
    old = re.compile(r'^%s(\.[0-9a-f]{%d})?%s$' % (re.escape(stem), HASH_LEN, re.escape(ext)))   # also the unversioned file
    for f in os.listdir(SITE):
        if f != new and old.match(f):
            os.remove(os.path.join(SITE, f))
            print('removed', os.path.normpath(os.path.join(SITE, f)), file=sys.stderr)
    with open(os.path.join(SITE, new), 'wb') as fh:
        fh.write(data)

    manifest = read_manifest()
    manifest[name] = new
    body = json.dumps(dict(sorted(manifest.items())), separators=(',', ':'))
    with open(MANIFEST, 'w', encoding='utf-8') as fh:
        fh.write(HEAD + body + ';\n')
    return new
